// Code generated by generate-registration. DO NOT EDIT.
//
// SetupGated defers controller startup until CRDs are installed (SafeStart).
// Setup starts all controllers immediately (RBAC fallback path).
// Each entry below owns and gates its own ProviderConfig controller(s)
// internally — there is no top-level, ungated ProviderConfig entry here.

package controller

import (
	"github.com/crossplane/crossplane-runtime/v2/pkg/controller"
	ctrl "sigs.k8s.io/controller-runtime"

	"github.com/crossplane-contrib/provider-k3s/internal/controller/cluster"
	"github.com/crossplane-contrib/provider-k3s/internal/controller/namespaced"
)

// SetupGated creates all controllers with safe-start (gate) support.
func SetupGated(mgr ctrl.Manager, o controller.Options) error {
	for _, setup := range []func(ctrl.Manager, controller.Options) error{
		cluster.SetupGated,
		namespaced.SetupGated,
	} {
		if err := setup(mgr, o); err != nil {
			return err
		}
	}
	return nil
}

// Setup creates all controllers without gate support (RBAC fallback path).
func Setup(mgr ctrl.Manager, o controller.Options) error {
	for _, setup := range []func(ctrl.Manager, controller.Options) error{
		cluster.Setup,
		namespaced.Setup,
	} {
		if err := setup(mgr, o); err != nil {
			return err
		}
	}
	return nil
}
