// Code generated by generate-registration. DO NOT EDIT.
//
// SetupGated defers MR controller startup until CRDs are installed (SafeStart).
// Setup starts all controllers immediately (RBAC fallback path).
// ProviderConfig (config.Setup) is NEVER gated — it must always be available.

package apis

import (
	clusterv1alpha1 "github.com/crossplane-contrib/provider-k3s/apis/cluster/v1alpha1"
	namespacedv1alpha1 "github.com/crossplane-contrib/provider-k3s/apis/namespaced/v1alpha1"
	"k8s.io/apimachinery/pkg/runtime"
)

// AddToSchemes may be used to add all resources defined in the project to a Scheme.
var AddToSchemes runtime.SchemeBuilder

func init() {
	AddToSchemes = append(AddToSchemes,
		clusterv1alpha1.SchemeBuilder.AddToScheme,
		namespacedv1alpha1.SchemeBuilder.AddToScheme,
	)
}

// AddToScheme adds all Resources to the Scheme.
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
