apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: ssh-credentials
type: Opaque
stringData:
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    <your-private-key-here>
    -----END OPENSSH PRIVATE KEY-----
---
apiVersion: k3s.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: ssh-ubuntu
spec:
  username: ubuntu
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: ssh-credentials
      key: ssh-privatekey
