apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-k3s
  annotations:
    meta.crossplane.io/maintainer: Christopher Haar <christopher.haar@upbound.io>
    meta.crossplane.io/source: github.com/crossplane-contrib/provider-k3s
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      A Crossplane provider for managing k3s clusters via SSH.
spec:
  capabilities:
    - safe-start
